fix: Use typings.Any instead of any
This fixes the following error:

    dacite.exceptions.WrongTypeError: wrong value type for field
"request.aggregations.argument" - should be "any" instead of value "15"
of type "int"